In [21]:
import pandas as pd
import json

In [2]:
df_scores = pd.read_parquet('../../../data/processed/individual_scores.parquet')

In [3]:
df_scores.shape

(42065, 41)

In [4]:
df_scores.columns

Index(['REF_PERSONNE', 'total_contracts', 'active_contracts',
       'product_variety', 'branch_variety', 'total_premiums_paid',
       'avg_premium_per_contract', 'max_premium', 'total_capital_assured',
       'avg_capital_per_contract', 'paid_ratio', 'total_paid_contracts',
       'total_unpaid_contracts', 'expired_contracts', 'canceled_contracts',
       'active_ratio', 'premium_per_contract_ratio', 'capital_premium_ratio',
       'product_density', 'loyalty_score', 'financial_score', 'payment_score',
       'NOM_PRENOM', 'DATE_NAISSANCE', 'LIEU_NAISSANCE', 'CODE_SEXE',
       'SITUATION_FAMILIALE', 'NUM_PIECE_IDENTITE', 'LIB_SECTEUR_ACTIVITE',
       'LIB_PROFESSION', 'VILLE', 'LIB_GOUVERNORAT', 'VILLE_GOUVERNORAT',
       'AGE', 'id_length', 'SECTEUR_ACTIVITE_GROUP', 'PROFESSION_GROUP',
       'final_client_score', 'client_segment', 'risk_profile', 'client_type'],
      dtype='object')

In [5]:
df_scores.head()

,REF_PERSONNE,total_contracts,active_contracts,product_variety,branch_variety,total_premiums_paid,avg_premium_per_contract,max_premium,total_capital_assured,avg_capital_per_contract,...,LIB_GOUVERNORAT,VILLE_GOUVERNORAT,AGE,id_length,SECTEUR_ACTIVITE_GROUP,PROFESSION_GROUP,final_client_score,client_segment,risk_profile,client_type
0,715,4.0,0.0,1.0,1.0,4679.51650,1169.879125,3103.33150,83750.0,20937.50,...,UNKNOWN,-,60,8,CADRES_SUPERIEURS,AUTRES_PROFESSIONS,0.459153,Prospect,High Risk,individual
1,1381,4.0,0.0,2.0,2.0,767.13500,191.783750,572.26000,21500.0,5375.00,...,UNKNOWN,NOUVELLE MEDINA -,63,8,SERVICES,TRANSPORTS,22.956586,Prospect,Medium Risk,individual
2,1947,4.0,1.0,2.0,2.0,2995.68482,748.921205,2911.53482,49125.0,12281.25,...,BEN AROUS,JBAL RSAS - BEN AROUS,55,8,COMMERCE_ET_VENTE,COMMERCE_ET_VENTE,26.177036,Prospect,Medium Risk,individual
3,2832,5.0,1.0,2.0,2.0,7581.40400,1516.280800,3964.54500,47500.0,9500.00,...,UNKNOWN,-,51,8,SANS_EMPLOI,NON_RENSEIGNE,21.935997,Prospect,Medium Risk,individual
4,3060,4.0,1.0,1.0,1.0,5640.94040,1410.235100,3804.16300,52000.0,13000.00,...,TUNIS,EL HRAIRIA - TUNIS,57,8,SANS_EMPLOI,NON_RENSEIGNE,9.929603,Prospect,High Risk,individual

In [6]:
df_individual_recommendations = pd.read_parquet('../../../data/processed/individual_recommendations.parquet')

In [7]:
df_individual_recommendations.shape

(42065, 13)

In [20]:
df_individual_recommendations.head()

,REF_PERSONNE,NOM_PRENOM,recommended_products,recommendation_count,client_score,client_segment,risk_profile,estimated_budget,AGE,PROFESSION_GROUP,SITUATION_FAMILIALE,SECTEUR_ACTIVITE_GROUP,client_type
0,715,PERSONNE_00001,"[{'confidence': 0.7013774597495528, 'product':...",3,0.459153,Prospect,High Risk,7019.27475,60.0,AUTRES_PROFESSIONS,MARIE,CADRES_SUPERIEURS,individual
1,1381,PERSONNE_00002,"[{'confidence': 0.7688697575034784, 'product':...",2,22.956586,Prospect,Medium Risk,1150.70250,63.0,TRANSPORTS,MARIE,SERVICES,individual
2,1947,PERSONNE_00003,"[{'confidence': 0.7785311071357583, 'product':...",2,26.177036,Prospect,Medium Risk,4493.52723,55.0,COMMERCE_ET_VENTE,MARIE,COMMERCE_ET_VENTE,individual
3,2832,PERSONNE_00004,"[{'confidence': 0.9658079904591532, 'product':...",3,21.935997,Prospect,Medium Risk,11372.10600,51.0,NON_RENSEIGNE,MARIE,SANS_EMPLOI,individual
4,3060,PERSONNE_00005,"[{'confidence': 0.7297888093818327, 'product':...",3,9.929603,Prospect,High Risk,8461.41060,57.0,NON_RENSEIGNE,MARIE,SANS_EMPLOI,individual

In [10]:
df_individual_recommendations.iloc[0]['recommended_products']

array([{'confidence': 0.7013774597495528, 'product': 'ASSURANCE VIE COMPLEMENT RETRAITE - HORIZON', 'reason': 'Based on client profile and scoring: 70.13774597495528/100', 'score': 70.13774597495528},
       {'confidence': 0.5013774597495528, 'product': 'ASSURANCE MIXTE VIE', 'reason': 'Based on client profile and scoring: 50.13774597495528/100', 'score': 50.13774597495528},
       {'confidence': 0.5013774597495528, 'product': 'RESPONSABILITE CIVILE', 'reason': 'Based on client profile and scoring: 50.13774597495528/100', 'score': 50.13774597495528}],
      dtype=object)

In [11]:
df_alerts = pd.read_parquet('../../../data/processed/alerts.parquet')

In [12]:
df_alerts.shape

(31058, 11)

In [15]:
df_alerts.iloc[0]['alert_message']

'Policy 2005301007671 (AUTOMOBILE) expires in -6981 days'

In [16]:
df_business_scores = pd.read_parquet('../../../data/processed/business_scores.parquet')

In [17]:
df_business_scores.head()

,REF_PERSONNE,RAISON_SOCIALE,MATRICULE_FISCALE,LIB_SECTEUR_ACTIVITE,LIB_ACTIVITE,VILLE,LIB_GOUVERNORAT,VILLE_GOUVERNORAT,SECTEUR_GROUP,ACTIVITE_GROUP,...,canceled_contracts,loyalty_score,financial_score,payment_score,final_client_score,size_adjustment,risk_adjustment,client_segment,risk_profile,client_type
0,12122,SOCIETE_000001,0000001W,SERVICES PERSONNELS,ACTIVITÃ‰S THERMALES ET DE THALASSOTHÃ‰RAPIE,NAN,NAN,-,SERVICES_ET_CONSEIL,AUTRES_ACTIVITES,...,1.0,0.000000,0.398604,0.000000,0.197309,1.0,1.1,Startup,High Risk,business
1,12145,SOCIETE_000002,0000002H,TRAVAIL DU BOIS ET FABRICATION D ARTICLES EN BOIS,FABRICATION D EMBALLAGES EN BOIS,NAN,NAN,-,AUTRES_SECTEURS,PRODUCTION_ET_FABRICATION,...,1.0,0.000000,0.115176,0.000000,0.057012,1.0,1.1,Startup,High Risk,business
2,12169,SOCIETE_000003,0000003M,INTERMÃ‰DIATION FINANCIÃˆRE,CRÃ‰DIT BAIL,NAN,NAN,-,AUTRES_SECTEURS,AUTRES_ACTIVITES,...,4.0,21.774487,0.360694,78.947368,31.982116,1.1,1.1,Small Business,Medium Risk,business
3,12431,SOCIETE_000004,0000004J,CONSTRUCTION,INSTALLATION D EAU ET DE GAZ,SFAX,NAN,SFAX -,INDUSTRIE_ET_CONSTRUCTION,AUTRES_ACTIVITES,...,1.0,14.856172,0.385573,97.872340,28.807460,1.1,0.9,Startup,Low Risk,business
4,12711,SOCIETE_000005,0000005F,TRAVAIL DU BOIS ET FABRICATION D ARTICLES EN BOIS,FABRICATION D EMBALLAGES EN BOIS,SFAX,NAN,SFAX -,AUTRES_SECTEURS,PRODUCTION_ET_FABRICATION,...,1.0,4.053890,0.099635,90.909091,29.025813,1.1,1.1,Startup,Low Risk,business

In [18]:
df_business_recommendations = pd.read_parquet('../../../data/processed/business_recommendations.parquet')

In [19]:
df_business_recommendations.head()

,REF_PERSONNE,RAISON_SOCIALE,recommended_products,recommendation_count,client_score,client_segment,risk_profile,estimated_budget,SECTEUR_GROUP,ACTIVITE_GROUP,BUSINESS_RISK_PROFILE,total_capital_assured,total_premiums_paid,client_type
0,12122,SOCIETE_000001,"[{'confidence': 0.5005919262540713, 'product':...",1,0.197309,Startup,High Risk,7659.44625,SERVICES_ET_CONSEIL,AUTRES_ACTIVITES,LOW_RISK,22100.00,5106.2975,business
1,12145,SOCIETE_000002,"[{'confidence': 0.5001710365223608, 'product':...",1,0.057012,Startup,High Risk,2217.75000,AUTRES_SECTEURS,PRODUCTION_ET_FABRICATION,LOW_RISK,33000.00,1478.5000,business
2,12169,SOCIETE_000003,"[{'confidence': 0.5959463478013383, 'product':...",1,31.982116,Small Business,Medium Risk,26665.14600,AUTRES_SECTEURS,AUTRES_ACTIVITES,LOW_RISK,603253.16,17776.7640,business
3,12431,SOCIETE_000004,"[{'confidence': 1.0, 'product': 'MULTIRISQUES ...",1,28.807460,Startup,Low Risk,31165.32300,INDUSTRIE_ET_CONSTRUCTION,AUTRES_ACTIVITES,HIGH_RISK,927000.00,20776.8820,business
4,12711,SOCIETE_000005,"[{'confidence': 0.5870774398147588, 'product':...",1,29.025813,Startup,Low Risk,6690.56700,AUTRES_SECTEURS,PRODUCTION_ET_FABRICATION,LOW_RISK,116000.00,4460.3780,business

In [23]:
df_individual_recommendations['recommended_products'] = df_individual_recommendations['recommended_products'].apply(
    lambda x: json.dumps(x.tolist()) if hasattr(x, 'tolist') else json.dumps(x)
)
df_business_recommendations['recommended_products']=df_business_recommendations['recommended_products'].apply(
    lambda x: json.dumps(x.tolist()) if hasattr(x, 'tolist') else json.dumps(x)
)

In [24]:
df_business_recommendations.head()

,REF_PERSONNE,RAISON_SOCIALE,recommended_products,recommendation_count,client_score,client_segment,risk_profile,estimated_budget,SECTEUR_GROUP,ACTIVITE_GROUP,BUSINESS_RISK_PROFILE,total_capital_assured,total_premiums_paid,client_type
0,12122,SOCIETE_000001,"[{""confidence"": 0.5005919262540713, ""product"":...",1,0.197309,Startup,High Risk,7659.44625,SERVICES_ET_CONSEIL,AUTRES_ACTIVITES,LOW_RISK,22100.00,5106.2975,business
1,12145,SOCIETE_000002,"[{""confidence"": 0.5001710365223608, ""product"":...",1,0.057012,Startup,High Risk,2217.75000,AUTRES_SECTEURS,PRODUCTION_ET_FABRICATION,LOW_RISK,33000.00,1478.5000,business
2,12169,SOCIETE_000003,"[{""confidence"": 0.5959463478013383, ""product"":...",1,31.982116,Small Business,Medium Risk,26665.14600,AUTRES_SECTEURS,AUTRES_ACTIVITES,LOW_RISK,603253.16,17776.7640,business
3,12431,SOCIETE_000004,"[{""confidence"": 1.0, ""product"": ""MULTIRISQUES ...",1,28.807460,Startup,Low Risk,31165.32300,INDUSTRIE_ET_CONSTRUCTION,AUTRES_ACTIVITES,HIGH_RISK,927000.00,20776.8820,business
4,12711,SOCIETE_000005,"[{""confidence"": 0.5870774398147588, ""product"":...",1,29.025813,Startup,Low Risk,6690.56700,AUTRES_SECTEURS,PRODUCTION_ET_FABRICATION,LOW_RISK,116000.00,4460.3780,business

In [25]:
df_business_recommendations.to_parquet('../../../data/processed/business_recommendations_v2.parquet')

In [26]:
df_individual_recommendations.to_parquet('../../../data/processed/individual_recommendations_v2.parquet')